// eslint-disable-next-line
export default {
  login: 'rOluochKe',
  id: 8114528,
  node_id: 'MDQ6VXNlcjgxMTQ1Mjg=',
  avatar_url: 'https://avatars.githubusercontent.com/u/8114528?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/rOluochKe',
  html_url: 'https://github.com/rOluochKe',
  followers_url: 'https://api.github.com/users/rOluochKe/followers',
  following_url:
    'https://api.github.com/users/rOluochKe/following{/other_user}',
  gists_url: 'https://api.github.com/users/rOluochKe/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/rOluochKe/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/rOluochKe/subscriptions',
  organizations_url: 'https://api.github.com/users/rOluochKe/orgs',
  repos_url: 'https://api.github.com/users/rOluochKe/repos',
  events_url: 'https://api.github.com/users/rOluochKe/events{/privacy}',
  received_events_url: 'https://api.github.com/users/rOluochKe/received_events',
  type: 'User',
  site_admin: false,
  name: 'Raymond Oluoch',
  company: null,
  blog: 'https://raymondoluoch.me/',
  location: 'Remote',
  email: null,
  hireable: true,
  bio: 'A Software Developer. I spend my whole day experimenting with JavaScript, Ruby, and Python. I build web applications that delight and inform. I do it well.',
  twitter_username: 'rOluochKe',
  public_repos: 92,
  public_gists: 1,
  followers: 40,
  following: 14,
  created_at: '2014-07-09T13:54:38Z',
  updated_at: '2021-08-09T14:11:32Z',
}
